name: python_stats_environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - plotly 
    - scikit-learn
    - pandas
    - matplotlib
    - numpy
    - scipy
    - pandas
    - statsmodels
    - seaborn
    - urllib
    - os
    - statsmodels.formula.api
    - matplotlib.pyplot
